export enum AuthError {
  ACCOUNT_ALREADY_EXISTS_FOR_EMAIL = 'ACCOUNT_ALREADY_EXISTS_FOR_EMAIL',
  ACCOUNT_ALREADY_EXISTS_FOR_USERNAME = 'ACCOUNT_ALREADY_EXISTS_FOR_USERNAME',
  ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT_DOES_NOT_EXIST',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
}
