export enum AuthError {
  ACCOUNT_ALREADY_EXISTS_FOR_EMAIL = 'ACCOUNT_ALREADY_EXISTS_FOR_EMAIL',
  ACCOUNT_ALREADY_EXISTS_FOR_USERNAME = 'ACCOUNT_ALREADY_EXISTS_FOR_USERNAME',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
}
