export enum ChatError {
  ILLEGAL_ACTION = 'ILLEGAL_ACTION',
  MESSAGE_MISSING = 'MESSAGE_MISSING',
  IMAGE_MISSING = 'IMAGE_MISSING',
  CHAT_UID_ILLEGAL = 'CHAT_UID_ILLEGAL',
  NOT_FRIENDS = 'NOT_FRIENDS',
}
